/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FeeManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burnBps"
      | "daoTreasury"
      | "process"
      | "rewardBps"
      | "rewardPool"
      | "setSplits"
      | "token"
      | "treasuryBps"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FeeProcessed" | "SplitsChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "burnBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daoTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "process",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "rewardBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rewardPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSplits",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasuryBps",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "burnBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "process", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rewardBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rewardPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSplits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryBps",
    data: BytesLike
  ): Result;
}

export namespace FeeProcessedEvent {
  export type InputTuple = [
    fee: BigNumberish,
    burned: BigNumberish,
    reward: BigNumberish,
    treasury: BigNumberish
  ];
  export type OutputTuple = [
    fee: bigint,
    burned: bigint,
    reward: bigint,
    treasury: bigint
  ];
  export interface OutputObject {
    fee: bigint;
    burned: bigint;
    reward: bigint;
    treasury: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitsChangedEvent {
  export type InputTuple = [
    burn: BigNumberish,
    reward: BigNumberish,
    treasury: BigNumberish
  ];
  export type OutputTuple = [burn: bigint, reward: bigint, treasury: bigint];
  export interface OutputObject {
    burn: bigint;
    reward: bigint;
    treasury: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeeManager extends BaseContract {
  connect(runner?: ContractRunner | null): FeeManager;
  waitForDeployment(): Promise<this>;

  interface: FeeManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burnBps: TypedContractMethod<[], [bigint], "view">;

  daoTreasury: TypedContractMethod<[], [string], "view">;

  process: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  rewardBps: TypedContractMethod<[], [bigint], "view">;

  rewardPool: TypedContractMethod<[], [string], "view">;

  setSplits: TypedContractMethod<
    [_burn: BigNumberish, _reward: BigNumberish, _treasury: BigNumberish],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  treasuryBps: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burnBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "daoTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "process"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSplits"
  ): TypedContractMethod<
    [_burn: BigNumberish, _reward: BigNumberish, _treasury: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasuryBps"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FeeProcessed"
  ): TypedContractEvent<
    FeeProcessedEvent.InputTuple,
    FeeProcessedEvent.OutputTuple,
    FeeProcessedEvent.OutputObject
  >;
  getEvent(
    key: "SplitsChanged"
  ): TypedContractEvent<
    SplitsChangedEvent.InputTuple,
    SplitsChangedEvent.OutputTuple,
    SplitsChangedEvent.OutputObject
  >;

  filters: {
    "FeeProcessed(uint256,uint256,uint256,uint256)": TypedContractEvent<
      FeeProcessedEvent.InputTuple,
      FeeProcessedEvent.OutputTuple,
      FeeProcessedEvent.OutputObject
    >;
    FeeProcessed: TypedContractEvent<
      FeeProcessedEvent.InputTuple,
      FeeProcessedEvent.OutputTuple,
      FeeProcessedEvent.OutputObject
    >;

    "SplitsChanged(uint16,uint16,uint16)": TypedContractEvent<
      SplitsChangedEvent.InputTuple,
      SplitsChangedEvent.OutputTuple,
      SplitsChangedEvent.OutputObject
    >;
    SplitsChanged: TypedContractEvent<
      SplitsChangedEvent.InputTuple,
      SplitsChangedEvent.OutputTuple,
      SplitsChangedEvent.OutputObject
    >;
  };
}
