/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ammPairSol from "./AMMPair.sol";
export type { ammPairSol };
export type { BORA } from "./BORA";
export type { FeeManager } from "./FeeManager";
export type { KYCAttestor } from "./KYCAttestor";
export type { LockupStaking } from "./LockupStaking";
export type { RewardDistributor } from "./RewardDistributor";
