/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface KYCAttestorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestor"
      | "owner"
      | "setAttestor"
      | "setVerified"
      | "verified"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AttestorSet" | "Verified"): EventFragment;

  encodeFunctionData(
    functionFragment: "attestor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAttestor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerified",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "verified",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "attestor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAttestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verified", data: BytesLike): Result;
}

export namespace AttestorSetEvent {
  export type InputTuple = [a: AddressLike, ok: boolean];
  export type OutputTuple = [a: string, ok: boolean];
  export interface OutputObject {
    a: string;
    ok: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedEvent {
  export type InputTuple = [user: AddressLike, ok: boolean];
  export type OutputTuple = [user: string, ok: boolean];
  export interface OutputObject {
    user: string;
    ok: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KYCAttestor extends BaseContract {
  connect(runner?: ContractRunner | null): KYCAttestor;
  waitForDeployment(): Promise<this>;

  interface: KYCAttestorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setAttestor: TypedContractMethod<
    [a: AddressLike, ok: boolean],
    [void],
    "nonpayable"
  >;

  setVerified: TypedContractMethod<
    [user: AddressLike, ok: boolean],
    [void],
    "nonpayable"
  >;

  verified: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAttestor"
  ): TypedContractMethod<[a: AddressLike, ok: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerified"
  ): TypedContractMethod<
    [user: AddressLike, ok: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verified"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "AttestorSet"
  ): TypedContractEvent<
    AttestorSetEvent.InputTuple,
    AttestorSetEvent.OutputTuple,
    AttestorSetEvent.OutputObject
  >;
  getEvent(
    key: "Verified"
  ): TypedContractEvent<
    VerifiedEvent.InputTuple,
    VerifiedEvent.OutputTuple,
    VerifiedEvent.OutputObject
  >;

  filters: {
    "AttestorSet(address,bool)": TypedContractEvent<
      AttestorSetEvent.InputTuple,
      AttestorSetEvent.OutputTuple,
      AttestorSetEvent.OutputObject
    >;
    AttestorSet: TypedContractEvent<
      AttestorSetEvent.InputTuple,
      AttestorSetEvent.OutputTuple,
      AttestorSetEvent.OutputObject
    >;

    "Verified(address,bool)": TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;
    Verified: TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;
  };
}
