/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeManager,
  IFeeManagerInterface,
} from "../../../contracts/AMMPair.sol/IFeeManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "process",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeManager__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeManagerInterface {
    return new Interface(_abi) as IFeeManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFeeManager {
    return new Contract(address, _abi, runner) as unknown as IFeeManager;
  }
}
