name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run cryptography tests
      run: python tests/test_crypto.py
    
    - name: Run consensus tests
      run: python tests/test_consensus.py
    
    - name: Test core modules
      run: |
        python core/cryptography.py
        python core/consensus.py
        python core/security.py
